### ISSUE TITLE
Issue when deleting an event

### ISSUE THREAD

**Issue by sqlilabs** [sqlilabs/WorkshopManager#26]
Execution exception
[PersistenceException: ERROR executing DML bindLog[] error[Cannot delete or update a parent row: a foreign key constraint fails (`workshopmanager`.`POTENTIAL_PARTICIPANTS`, CONSTRAINT `fk_POTENTIAL_PARTICIPANTS_WORKSHOP_01` FOREIGN KEY (`workshop_id`) REFERENCES `WORKSHOP` (`id`))]]
In /work/Development/Workspaces/SQLILabs/WorkshopManager/workshop-manager/app/controllers/WorkshopController.java at line 132.
129 @Transactional
130 public static Result deleteWorkshop(Long id) {
131     Workshop ws = Workshop.find.byId(id);
132     Ebean.delete(ws);
133
134     for (String key : request().headers().keySet()) {
135         System.out.println(key);
136     }

---
- Bitbucket: https://bitbucket.org/sqlilabs/workshop-manager/issue/24
- Originally Reported By: [Yannick Chartois](http://bitbucket.org/ychartois)
- Originally Created At: 2013-04-10T00:00:38.112

**Comment by sqlilabs** [comment]
non reproductible

---

Original Comment By: [Yannick Chartois](http://bitbucket.org/ychartois)

**Comment by ychartois** [comment]
a cascade=CascadeType.ALL was missing on the table: POTENTIAL_PARTICIPANTS
