### ISSUE TITLE
Profile Picture

### ISSUE THREAD

**Issue by sqlilabs** [sqlilabs/WorkshopManager#34]
Quand on change la photo du profil la page ne se rafraichit pas (les workshops auxquels on s'est inscrit affichent toujours l'ancienne photo)

---
- Bitbucket: https://bitbucket.org/sqlilabs/workshop-manager/issue/32
- Originally Reported By: Anonymous
- Originally Created At: 2013-05-21T10:17:20.636

**Comment by sqlilabs** [comment]
Seule l'image du profil se rafraîchie en Ajax, les autres images sont rafraîchies au prochain chargement de la page

---

Original Comment By: [Yannick Chartois](http://bitbucket.org/ychartois)

**Comment by ychartois** [comment]
fixed in main.js
