### ISSUE TITLE
Ajout d'un datepicker pour les champs date

### ISSUE THREAD

**Issue by sqlilabs** [sqlilabs/WorkshopManager#39]
Il serait plus pratique de rajouter un date picker jquery ui à côté des champs de saisie de type date

---
- Bitbucket: https://bitbucket.org/sqlilabs/workshop-manager/issue/37
- Originally Reported By: [ ](http://bitbucket.org/vincent_dubois)
- Originally Created At: 2013-05-23T12:23:43.549

**Comment by sqlilabs** [comment]
Le datepicker actuel n'a pas l'air de fonctionner sur certain navigateur, je vais essayé de le remplacer par autre chose... 

---

Original Comment By: [Yannick Chartois](http://bitbucket.org/ychartois)

**Comment by ychartois** [comment]
date picker added
