### ISSUE TITLE
User roles administration page

### ISSUE THREAD

**Issue by sqlilabs** [sqlilabs/WorkshopManager#45]
it miss a page to do the admin or the user roles

Page d'administration des user
Il manquerai une page d'admin des droits pour ne pas être obligé de le faire directement en base...

---
- Bitbucket: https://bitbucket.org/sqlilabs/workshop-manager/issue/43
- Originally Reported By: [Yannick Chartois](http://bitbucket.org/ychartois)
- Originally Created At: 2013-06-08T12:40:44.321

**Comment by ychartois** [comment]
done
